### ISSUE TITLE
Timestamp Format Option

### ISSUE THREAD

**Issue by rasyidstat** [JBGruber/rwhatsapp#1]
My timestamp is parsed incorrectly since the format is MM/dd/yy, hh:mm
I think you should add an option to parse with different timestamp format.

**Comment by JBGruber** [comment]
Thanks for letting me know. I was thinking about this but wanted to keep it as automatic as possible. However, this is a time format that I've never encountered before and so I think it's perfectly possible there might be others out there.

I included it in the list of formats that are automatically detected and also added an argument to provide custom time formats, as you suggested.

Can you let me know if this works for you now?

**Comment by rasyidstat** [comment]
Cool
Thanks, it works now
