### ISSUE TITLE
Unable to parse emoji column

### ISSUE THREAD

**Issue by cjcarpenter1** [JBGruber/rwhatsapp#2]
> rlang::last_error()
<error>
message: `by` can't contain join column `emoji` which is missing from LHS
class:   `rlang_error`
backtrace:
  1. rwhatsapp::rwa_read(history)
  5. rwhatsapp:::rwa_add_emoji(tbl)
  7. dplyr:::left_join.tbl_df(out, rwhatsapp::emojis, by = "emoji")
  9. dplyr:::common_by.character(by, x, y)
 10. dplyr:::common_by.list(by, x, y)
 11. dplyr:::bad_args(...)
 12. dplyr:::glubort(fmt_args(args), ..., .envir = .envir)
Call `rlang::last_trace()` to see the full backtrace

**Comment by JBGruber** [comment]
Is it possible that your `history` object is empty? I just tried to replicate your issue and the only way I can see this happening is:

```
library("rwhatsapp")
chat <- rwa_read("")
```

I wrote a small update to display a more informative error if this accidentally happens.

If this was not your problem, could you please provide the code you used just before this error occurred? Your `sessionInfo()` might also help.

**Comment by JBGruber** [comment]
Problem seems to be solved.
