### ISSUE TITLE
Inquiry for reading txt files containing characteristics of Chinese language

### ISSUE THREAD

**Issue by vickybrtyy89** [JBGruber/rwhatsapp#23]
Thank you so much for this package. It works well with files in English. However, when I am trying to import files in Chinese, Rstudio cannot show Chinese characteristics properly. 
![Capture](https://user-images.githubusercontent.com/86699702/123895741-eb3c9200-d992-11eb-90f6-7d047ac52fc5.PNG)
Meanwhile, the Chinese characteristics can be shown in the environment.
![image](https://user-images.githubusercontent.com/86699702/123895881-25a62f00-d993-11eb-9638-2a51e756311f.png)
so I am wondering how to import the Chinese words properly for future analysis.
Thank you so much for your help.

**Comment by JBGruber** [comment]
Could you try and export your `data.frame` to a csv file and open it in another application (e.g., Notepad or Excel etc.)? That means something like:

```
library("rwhatsapp")
chat <- rwa_read(history)
rio::export(chat, "test.csv")
```
In my experience, `R` is extremely good with basically all kinds of characters, agnostic of the language. But `RStudio` isn't necessarily. That means your data might be *stored* correctly in `R` but is not *displayed* correctly. In the latter case, this would be an `RStudio` issue that I can't really help you with. By exporting the data and opening it in an application that you know is capable of displaying Chinese characters, you can test which problem you have.

**Comment by vickybrtyy89** [comment]
Thank you so much for your reply. I checked the results in R and it works really well.
