### ISSUE TITLE
The rwa_read command doesn't work when I import my WhatsApp chat.xt file.

### ISSUE THREAD

**Issue by Kanda291** [JBGruber/rwhatsapp#25]
My problem is with the rwa_read command when I’m importing a WhatsApp chat text file. When my chat text file contained about 1200 lines, I had NO problem importing it. But with a larger chat file (with about 6000 lines), when I use the following command in my R, 
mychat_df<- rwa_read("~/WhatsApp_Analysis/Presidency_chat.txt")
after 5 to 6 minutes of processing time, I get the error message:    Time conversion did not work correctly. Provide a custom format … 
Not sure how I provide a custom format in the rwa_read command. In my WhatsApp chat text file, the time format is [mm/dd/yy, hh:mm:ss AM/PM]. The structure of the rwa_read is:
rwa_read(x, tz = NULL, format = NULL, verbose = FALSE, encoding = "UTF-8", ...)
What do I substitute after format = ?  

Aside:On my desktop, I have the RStudio (Version 1.1.383 – 2009-2017) and my R version is 3.6.1 (2019-07-05)). Would very much appreciate your input.

**Comment by JBGruber** [comment]
You can try this date format: `rwa_read("~/WhatsApp_Analysis/Presidency_chat.txt", format = "MM/dd/yy hh:mm:ss a")`. That should also make things a little faster. If this doesn't work, you can check `?stringi::stri_datetime_format` for the correct format. But the described format should be automatically detected.

FYI: My private test file which I based the README on has 17,000 lines and is parsed without an issue.

If you do not succeed with a custom time format, can you post the first 10 or so lines of your `Presidency_chat.txt` file here? It's okay if you want to replace the text and names with `xxx` if they contain private information.

**Comment by Kanda291** [comment]
Thanks for your fast response. I'm still getting the same error message -     Time conversion did not work correctly. Provide a custom format or add an issue at www.github.com/JBGruber/rwhatsapp. But I got this error message within 90 seconds. 
[Presidency_chatAug1.txt](https://github.com/JBGruber/rwhatsapp/files/6946216/Presidency_chatAug1.txt)
I've attached the entire file. Thanks again.
