### ISSUE TITLE
Consistant problems to read the TXT

### ISSUE THREAD

**Issue by GiuPolli** [JBGruber/rwhatsapp#31]
There is an error that keeps appearing to me sometimes when I run a code to read a TXT

**chat_clean_Arena <- rwa_read("Arena Divulgacao - Imperium.txt")
Error in split.default(lookup$emoji, lookup$id) : 
  first argument must be a vector**
  
  
 - It is something related to some of the chat message itself in the TXT, because I deleted some messages and than it worked.
 - But I had a hard time to discover which message was triggering this error, I had to delete one by one until the code works.
 - And I couldn't find a padron between the messages to explain why this is happening.
  
  I hope you can help me, is driving me crazy.
  
  I will attach a file that is showing this error
  [Arena Divulgacao - Imperium.txt](https://github.com/JBGruber/rwhatsapp/files/13522452/Arena.Divulgacao.-.Imperium.txt)
  ( this one I couldnt find which was the error message) and put here some of the chat messages that triggered the problem previouly in another file, as you can see, one of the messages don't even have an emoji into it:
  
[23/08/2023 20:28:08] Moara Souto Vieira: Oi lindezas tudo bem por aí? Hj é dia de relato por aqui..

Como contei para vcs semana passada eu estou bem reflexiva sobre carreira/trabalho.

Em 2020, sai de uma empresa onde trabalhava 10 anos como Gestora de RH.Onde tinha uma posição estável digamos assim, mas não fazia mais meus olhos brilharem, vivia não concordando com os valores da empresa e isso me machucava muito.

Quando saí, foi uma mistura de sentimentos,veio alívio, medo, insegurança e certeza que era o sinal que eu precisava….

Mas, claro que o que me faltava muito era clareza do que queria…naquele momento só tinha clareza do que não queria.. Já é um passo sabe.. Eu já sabia que ali não me energizava mais…

E fui caminhando aos poucos, estudando, conversando com muita gente para começar a trilhar minha mudança de carreira… na verdade temos muito medo do incerto, do novo e do que não conhecemos…Hoje tenho certeza que devemos ir com medo mesmo…. O medo faz parte da vida, ele sempre estará presente, ele quer dizer que estamos em caminhos novos e que a nossa mente ainda não se adaptou sabe…

Depois de 3 anos ainda continuo trilhando meu caminho, nada tá resolvido e seguro.. E é assim a vida..Sempre estaremos em movimento. Mas com certeza não estou no mesmo lugar, e isso já é lindo demais e tem que ser comemorado não é mesmo?

Vou deixar aqui, uma carta para o medo que eu sempre leio pra mim…

_Desejo que vocês curtam 
Beijokas 😙

[25/08/2023 18:30:01] Moara Souto Vieira: Filhos, idealizações e felicidade

“Nunca idealize os outros. Eles nunca vão alcançar as suas expectativas.” ~ Leo Buscaglia

Oi meninas, sextou… e queria trazer um texto que li em um blog e achei muito interessante sobre o que muitas vezes temos que nos atentar para não idealizarmos a vida  e carreira de nossos filhos.

https://www.lagartavirapupa.com.br/post/filhos-idealiza%C3%A7%C3%B5es-e-felicidade

E como a gente pode ajudar nossos filhos a encontrar suas aptidões e habilidades?

Uma delas é observar seus interesses e hobbies, incentivando-os a explorar diferentes atividades relacionadas a esses temas. Além disso, é importante que os pais ofereçam um ambiente seguro e acolhedor para que seus filhos possam se expressar livremente e compartilhar suas ideias e pensamentos.

*Conta pra gente como que vocês estimulam  as habilidades por aí nas crias?*

[30/08/2023 17:08:58] Moara Souto Vieira: Fase 6- Finanças

“Não importa quem você é ou qual é sua idade: se quiser conquistar sucesso permanente e sustentável, sua motivação precisa vir de dentro. (…) Deve ser pessoal, ter raízes profundas e fazer parte de seus pensamentos mais íntimos.  Paul J. Meyer –

Historicamente afastadas do mundo das finanças, mulheres devem aprender a lidar com dinheiro desde cedo para que possam assumir o protagonismo financeiro. O quanto você entende de finanças?

De acordo com um estudo do Banco de Investimentos Merrill Lynch, 61% das mulheres preferem falar sobre a própria morte do que sobre dinheiro. O resultado mostra que, para elas, o dinheiro supera um dos maiores tabus de nossa sociedade que é a morte. Muitas razões podem explicar esse medo de tratar o tema. Um deles é o fato de que até pouco tempo atrás as mulheres não podiam cuidar da sua própria vida financeira. No Brasil, as mulheres tiveram direito de ter sua própria conta bancária somente na década de 1960. Antes disso, mulheres casadas precisavam da autorização do marido para trabalhar fora. 
Essa parte da roda da vida está ligada às suas finanças. Você está ganhando dinheiro suficiente para manter o padrão de vida que você deseja? Veja, não é sobre ganhar mais dinheiro, é sobre ter o suficiente para bancar o que você almeja. 

🚩Cuidar do pilar finanças em nossa roda da vida envolve algumas práticas importantes:

📝Orçamento: Faça um planejamento financeiro, estabelecendo metas e acompanhando seus gastos e receitas. Isso ajudará a controlar seu dinheiro de forma mais eficiente.

🤑Poupança: Reserve uma parte de sua renda para economizar regularmente. Isso pode ser útil para lidar com imprevistos e alcançar objetivos financeiros de longo prazo.

💸Investimentos: Considere investir seu dinheiro de forma inteligente, levando em conta seu perfil de risco e objetivos financeiros. Consultar um profissional pode ser útil nesse processo.

🚨Dívidas: Gerencie suas dívidas de forma responsável, evitando acumular juros altos. Priorize o pagamento das dívidas com taxas mais elevadas.

👩‍🏫Educação financeira: Busque conhecimento sobre finanças pessoais e invista em sua educação financeira. Isso o ajudará a tomar decisões mais informadas e a alcançar uma maior estabilidade financeira.

Lembre-se de que cada pessoa tem circunstâncias financeiras únicas, portanto, é importante adaptar essas práticas às suas necessidades e objetivos individuais.

Bora fazer dinheiro 💰  perfeitas😍😍😍

**Comment by JBGruber** [comment]
By pure chance, the regular expression for identifying datetimes fits 40% of your messages. So the package thinks it has the right date format, which leads to catastrophic failure down the line. Thanks for filing the issue, I made the heuristic more robuts now. Should work with:

``` r
remotes::install_github("JBGruber/rwhatsapp")
#> Downloading GitHub repo JBGruber/rwhatsapp@HEAD
#> 
#> ── R CMD build ─────────────────────────────────────────────────────────────────
#> * checking for file ‘/tmp/Rtmph6crEw/remotes27f874400f0cb/JBGruber-rwhatsapp-bced4e1/DESCRIPTION’ ... OK
#> * preparing ‘rwhatsapp’:
#> * checking DESCRIPTION meta-information ... OK
#> * checking for LF line-endings in source and make files and shell scripts
#> * checking for empty or unneeded directories
#> * building ‘rwhatsapp_0.2.4.9000.tar.gz’
#> Installing package into '/home/johannes/R/x86_64-pc-linux-gnu-library/4.3'
#> (as 'lib' is unspecified)
curl::curl_download("https://github.com/JBGruber/rwhatsapp/files/13522452/Arena.Divulgacao.-.Imperium.txt", "hist.txt")
rwhatsapp::rwa_read(x = "hist.txt")
#> # A tibble: 928 × 6
#>    time                author                     text  source emoji  emoji_name
#>    <dttm>              <fct>                      <chr> <chr>  <list> <list>    
#>  1 2023-09-09 13:08:13 📣 Arena Divulgação - Imp… "‎As … hist.… <NULL> <NULL>    
#>  2 2023-09-09 13:08:13 ~ Matheus Mendonça         "‎~ M… hist.… <NULL> <NULL>    
#>  3 2023-10-24 20:08:08 📣 Arena Divulgação - Imp… "‎Voc… hist.… <NULL> <NULL>    
#>  4 2023-10-25 10:27:20 ~ Aguinaldo Santos         "‎~ E… hist.… <NULL> <NULL>    
#>  5 2023-10-25 10:32:53 ~ Priscilla Oliveira       "‎~ E… hist.… <NULL> <NULL>    
#>  6 2023-10-25 12:17:53 ~ Morena                   "Cur… hist.… <chr>  <chr [1]> 
#>  7 2023-10-25 12:18:20 ~ Morena                   "Que… hist.… <chr>  <chr [1]> 
#>  8 2023-10-25 12:18:38 ~ Morena                   "‎Men… hist.… <NULL> <NULL>    
#>  9 2023-10-25 12:28:55 ~ Caio Teixeira            "‎fig… hist.… <NULL> <NULL>    
#> 10 2023-10-25 12:29:28 ~ Caio Teixeira            "Fei… hist.… <chr>  <chr [4]> 
#> # ℹ 918 more rows
```

<sup>Created on 2023-12-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by GiuPolli** [comment]
Now the code is not being interrupted by the error and the object is being created. But the table chat is completely messed up, with many messages beig read as one. The aurthor collumn also appears to be messed.

![image](https://github.com/JBGruber/rwhatsapp/assets/92661106/49a92401-4a05-490f-97f6-917e3b34be51)

**Comment by JBGruber** [comment]
Thanks for the update. It seems I was a bit hasty marking this as resolved. I complelty overhauled the heuristic for guessing the correct time format. I think it looks much better now, but let me kniow if you still experience issues.
