### ISSUE TITLE
Error in cbind_all

### ISSUE THREAD

**Issue by breyesr** [JBGruber/rwhatsapp#4]
Hi, I'm sorry if this is a very basic issue I've tried to read a couple files and I get this error for some of the files:
Error in cbind_all(x) : Argument 2 must be length 3471, not 3470

What should I be looking to fix here if it's on my files?

**Comment by JBGruber** [comment]
I haven't seen this error before, very odd. However, `cbind_all` is an internal `dplyr` function and I recently removed all `dplyr` code to make the package a bit lighter in terms of dependencies. So I think the error might dissapear if you use the development version of the package instead: `devtools::install_github("JBGruber/rwhatsapp")`. 

Let me know if you get a different error.

**Comment by breyesr** [comment]
Yes! That fixed it, thanks!
