### ISSUE TITLE
Unidentified Emojis

### ISSUE THREAD

**Issue by mapale1** [JBGruber/rwhatsapp#5]
Many of the emojis are not identified, for example, <U + 0001F913> <U + 0001F914> <U + 0001F644>

**Comment by JBGruber** [comment]
Thanks for reporting. However, I can't reproduce your issue. Assuming the emojis below are the one you're having problems with, they parse without a problem. 

``` r
x <- c(
  "05/11/2019, 08:52 - Johannes Gruber: Is there a problem with this emoji?",
  "05/11/2019, 08:52 - Johannes Gruber: 🤓",
  "05/11/2019, 09:00 - Johannes Gruber: 🤔",
  "05/11/2019, 09:00 - Johannes Gruber: 🙄"
)

library(tidyr)
library(dplyr)

rwhatsapp::rwa_read(x) %>% 
  unnest(c(emoji, emoji_name)) %>% 
  left_join(rwhatsapp::emojis, by = "emoji")
#> # A tibble: 3 x 8
#>   time                author  text  source emoji emoji_name name  hex_runes
#>   <dttm>              <fct>   <chr> <chr>  <chr> <chr>      <chr> <chr>    
#> 1 2019-11-05 08:52:49 Johann… 🤓    text … 🤓    nerd face  nerd… 1F913    
#> 2 2019-11-05 09:00:49 Johann… 🤔    text … 🤔    thinking … thin… 1F914    
#> 3 2019-11-05 09:00:49 Johann… 🙄    text … 🙄    face with… face… 1F644
```
<sup>Created on 2019-11-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Maybe you can share an excerpt of your chat log with which you have the problems? I'm matching emojis against a data.frame of known emojis. So it is prone to error theoretically as I couldn't find the exact Unicode characters Whatsapp is using.

**Comment by shbkukuk** [comment]
many time i tried to work this project for my data but i cant get it on succesfull. how can i use this code blog. thanks for regards

**Comment by JBGruber** [comment]
Please give a more detailed description of what you are trying to do and what isn't working for you. Ideally provide a [reproducible example](http://stackoverflow.com/questions/5963269) of what exactly is causing an error for you (e.g., with [this](https://reprex.tidyverse.org/)) .

**Comment by pintodossantos** [comment]
Interestingly I seem to have a similar problem, but there are differences between the output in an Rmarkdown, ggplot and console output...
Rmarkdown:
<img width="830" alt="Bildschirmfoto 2019-11-13 um 13 01 42" src="https://user-images.githubusercontent.com/33542503/68762100-c48ee380-0615-11ea-86d5-61c952ba5d7a.png">
Console:
<img width="830" alt="Bildschirmfoto 2019-11-13 um 13 02 36" src="https://user-images.githubusercontent.com/33542503/68762165-eee0a100-0615-11ea-955d-14b7b93974a0.png">
GGplot:
<img width="760" alt="Bildschirmfoto 2019-11-13 um 13 03 43" src="https://user-images.githubusercontent.com/33542503/68762303-349d6980-0616-11ea-9030-c5eff6f111cf.png">

**Comment by JBGruber** [comment]
Hi @pintodossantos.This is an i[ssue with the font `ggplot2` is using by default](https://github.com/JBGruber/rwhatsapp/issues/3#issuecomment-542101757), not with `rwhatsapp`, which seems to do fine here. Are you using a Mac? I outlined a solution [here](https://github.com/JBGruber/rwhatsapp/issues/3#issuecomment-546586930).

**Comment by pintodossantos** [comment]
Thanks! I understand the ggplot part, but the Rmarkdown?

**Comment by JBGruber** [comment]
Okay, now I get it. I don't really know a lot about how RStudio is displaying RMarkdown code chunks. I tried this on my machine and it works fine. On rstudio.cloud I get the same result as you. In both cases, the output looks fine when rendered to html. I guess this is another font or encoding issue. But the issue is only displaying the emojis. The data itself is correct. 

What operating system do you use? And do you have the newest version of RStudio?

**Comment by pintodossantos** [comment]
```
> version
               _                           
platform       x86_64-apple-darwin15.6.0   
arch           x86_64                      
os             darwin15.6.0                
system         x86_64, darwin15.6.0        
status                                     
major          3                           
minor          6.1                         
year           2019                        
month          07                          
day            05                          
svn rev        76782                       
language       R                           
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes
```
and
```
> RStudio.Version()$version
[1] ‘1.2.5001’
```

**Comment by JBGruber** [comment]
I don't think this issue has anything to do with `rwhatsapp`. Rather it is a problem with the printing method in RStudio on some systems.

If you explicitly call a different printing method it should work for tables as well. For example something like:

```
emojis <- rwhatsapp::rwa_read(x) %>% 
  unnest(c(emoji, emoji_name)) %>% 
  left_join(rwhatsapp::emojis, by = "emoji")

emojis %>% 
  knitr::kable()
```

or:

```
emojis %>% 
  DT::datatable()
```
