### ISSUE TITLE
rwa_read issue

### ISSUE THREAD

**Issue by dbnkkk** [JBGruber/rwhatsapp#6]
Hi, thanks for the functions, very helpful.

However, rwa_read is not able to read msgs consisting of more than 2 lines. The function just picks up the top 2 lines of the msg. Are there any parameter settings to correct this?

Thanks!
Dobrin

**Comment by JBGruber** [comment]
:open_mouth: no idea how I missed that! But should work now with the dev version:

``` r
x <- c(
  "05/11/2019, 08:52 - Johannes Gruber: Is there a problem with this longer messages?",
  "05/11/2019, 08:52 - Johannes Gruber: Let's say this is a long message.", 
  "Which is split over several lines by WhatsApp.", 
  "",
  "And the user also leaves a blank line for the end of a paragraph",
  "Can rwhatsapp still read this?"
)

df <- rwhatsapp::rwa_read(x)
df$text
#> [1] "Is there a problem with this longer messages?"                                                                                                                                      
#> [2] "Let's say this is a long message.\nWhich is split over several lines by WhatsApp.\nAnd the user also leaves a blank line for the end of a paragraph\nCan rwhatsapp still read this?"
```

<sup>Created on 2019-11-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Thanks for reporting!

**Comment by dbnkkk** [comment]
thanks vm for sorting it out so quickly!

do i now need to just reinstall the R package to use the amended function? (sry if it is a stupid question)

**Comment by JBGruber** [comment]
Yes! It should work after you update the package using:

```
devtools::install_github("JBGruber/rwhatsapp")
```

**Comment by dbnkkk** [comment]
thanks Johannes, can confirm works fine here;]

**Comment by JBGruber** [comment]
Great!
