### ISSUE TITLE
Cbind all - argument lengths

### ISSUE THREAD

**Issue by Mageshpoondi** [JBGruber/rwhatsapp#7]
I tried working with messages from two groups.  The rwa_read() worked well with one group whereas with the second group I was getting this message.

Error in cbind_all(x) : Argument 2 must be length 4382, not 4381

The export process was exactly the same for both.  Any thoughts.

**Comment by JBGruber** [comment]
Thanks for reporting. It seems to be a duplicate of issue #4 though. Please install the newest development version with `remotes::install_github("JBGruber/rwhatsapp")`, then it should work. I'll update the package on CRAN as soon as I have the time (hopefully soon).

**Comment by Mageshpoondi** [comment]
Excellent!!! Worked straightaway.
Best
Magesh.

**Comment by Mageshpoondi** [comment]
Excellent!!  Thank you.  Worked perfectly.
