### ISSUE TITLE
Chat Androide 

### ISSUE THREAD

**Issue by Lucasalam** [JBGruber/rwhatsapp#9]
Hola, exporto el chat de whatsapp de Android me de da error de formato 

"18/12/19 15:57 - MARCELO gomez: Estoy de acuerdo!",
"18/12/19 15:58 - Débora Valeska: Yo te voto 🙋🏽",
"18/12/19 16:04 - Lopez W EsCristO: Yo pienso lo mismo")

Show in New WindowClear OutputExpand/Collapse Output
Time conversion did not work correctly. Provide a custom format or add an issue at 

chat <- rwa_read("chat00 .txt", format= "dd/MM/yyyy ' ' HH:mm ")

**Comment by JBGruber** [comment]
I just wrote a small update which should take care of this format. Install with `remotes::install_github("JBGruber/rwhatsapp")`.

``` r
x <- c("18/12/19 15:57 - MARCELO gomez: Estoy de acuerdo!",
       "18/12/19 15:58 - Débora Valeska: Yo te voto 🙋🏽",
       "18/12/19 16:04 - Lopez W EsCristO: Yo pienso lo mismo")

rwhatsapp::rwa_read(x)
#> # A tibble: 3 x 6
#>   time                author         text            source   emoji   emoji_name
#>   <dttm>              <fct>          <chr>           <chr>    <list>  <list>    
#> 1 2019-12-18 15:57:04 MARCELO gomez  Estoy de acuer… text in… <NULL>  <NULL>    
#> 2 2019-12-18 15:58:04 Débora Valeska Yo te voto 🙋🏽   text in… <chr [… <chr [1]> 
#> 3 2019-12-18 16:04:04 Lopez W EsCri… Yo pienso lo m… text in… <NULL>  <NULL>
```

<sup>Created on 2019-12-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
